---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kustomize.toolkit.fluxcd.io/v1beta1","kind":"Kustomization","metadata":{"annotations":{},"labels":{"kustomize.toolkit.fluxcd.io/checksum":"4e3f815755ac3353dc090ff39b3cc01cff6b2141","kustomize.toolkit.fluxcd.io/name":"flux-system","kustomize.toolkit.fluxcd.io/namespace":"flux-system"},"name":"flux-system","namespace":"flux-system"},"spec":{"interval":"10m0s","path":"./clusters/my-cluster","prune":true,"sourceRef":{"kind":"GitRepository","name":"flux-system"},"validation":"client"}}
  labels:
    kustomize.toolkit.fluxcd.io/checksum: 4e3f815755ac3353dc090ff39b3cc01cff6b2141
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kustomize.toolkit.fluxcd.io/v1beta1","kind":"Kustomization","metadata":{"annotations":{},"labels":{"kustomize.toolkit.fluxcd.io/checksum":"4e3f815755ac3353dc090ff39b3cc01cff6b2141","kustomize.toolkit.fluxcd.io/name":"flux-system","kustomize.toolkit.fluxcd.io/namespace":"flux-system"},"name":"podinfo","namespace":"flux-system"},"spec":{"interval":"5m0s","path":"./kustomize","prune":true,"sourceRef":{"kind":"GitRepository","name":"podinfo"},"validation":"client"}}
  labels:
    kustomize.toolkit.fluxcd.io/checksum: 4e3f815755ac3353dc090ff39b3cc01cff6b2141
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  validation: client

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kustomize.toolkit.fluxcd.io/v1beta1","kind":"Kustomization","metadata":{"annotations":{},"labels":{"kustomize.toolkit.fluxcd.io/checksum":"4e3f815755ac3353dc090ff39b3cc01cff6b2141","kustomize.toolkit.fluxcd.io/name":"flux-system","kustomize.toolkit.fluxcd.io/namespace":"flux-system"},"name":"sqlbackend","namespace":"flux-system"},"spec":{"interval":"5m0s","path":"./kustomize/sql/overlay/local","prune":true,"sourceRef":{"kind":"GitRepository","name":"sqlbackendsource"},"validation":"client"}}
  labels:
    kustomize.toolkit.fluxcd.io/checksum: 4e3f815755ac3353dc090ff39b3cc01cff6b2141
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: sqlbackend
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize/sql/overlay/local
  prune: true
  sourceRef:
    kind: GitRepository
    name: sqlbackendsource
  validation: client

