apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  labels:
    app: poi
spec:
  selector:
    matchLabels:
      app: poi
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
        prometheus.io/scheme: "http"
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: demoacrk8s.azurecr.io/demoacrk8s/poi
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "1000m"
        env: 
          - name: "SQL_USER"
            value: "SA"     
          - name: "SQL_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: mssql
                key: SA_PASSWORD 
          - name: "SQL_SERVER"
            value: "mssql-deployment"
          - name: "SQL_DBNAME"
            value: "mydrivingDB"
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Local"
---
apiVersion: v1
kind: Service 
metadata:
  name: poi
spec:
  selector:
    app: poi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80