apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava
spec:
  selector:
    matchLabels:
      app: userjava
  replicas: 1
  template:
    metadata:
      labels:
        app: userjava
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
        prometheus.io/scheme: "http"
    spec:
      containers:
      - name: userjava
        image: demoacrk8s.azurecr.io/demoacrk8s/user-java
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env: 
          - name: "SQL_USER"
            value: "SA"     
          - name: "SQL_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: mssql
                key: SA_PASSWORD 
          - name: "SQL_SERVER"
            value: "mssql-deployment"
          - name: "SQL_DBNAME"
            value: "mydrivingDB"
      
---
apiVersion: v1
kind: Service
metadata:
  name: userjava
spec:
  selector:
    app: userjava
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
