apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-demok8svault-user-msi
spec:
  provider: azure
  secretObjects:                             
  - data:
    - key: SA_PASSWORD                          
      objectName: sqlpassword                        
    secretName: mssql                     
    type: Opaque        
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"  
    userAssignedIdentityID: "5015a570-ba7f-446c-aee2-f6915395933f"
    keyvaultName: "demoaksvault"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: sqlpassword
          objectType: secret       
          objectVersion: ""        
    tenantId: "5b973f99-77df-4beb-b27d-aa0c70b8482c"