---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-secrets-store-provider-azure
  namespace: flux-system
spec:
  chart:
    spec:
      chart: csi-secrets-store-provider-azure
      sourceRef:
        kind: HelmRepository
        name: csi-secrets-store-provider-azure
      version: 0.0.16
  interval: 5m0s

