---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ingressapp
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize/infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitopsflux
  validation: client
  dependsOn: 
    - name : poiapp
    - name : tripsapp
    - name : tripviewerapp
    - name : userapp
    - name : userjavaapp



