---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tripsapp
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize/apps/trips/overlay/local
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitopsflux
  validation: client
  dependsOn: 
    - name : sqlbackend
