apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  labels:
    app: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
        prometheus.io/scheme: "http"
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: demoacrk8s.azurecr.io/demoacrk8s/trips
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "1000m"
        env: 
          - name: "SQL_USER"
            value: "SA"     
          - name: "SQL_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: mssql
                key: SA_PASSWORD 
          - name: "SQL_SERVER"
            value: "mssql-deployment"
          - name: "SQL_DBNAME"
            value: "mydrivingDB"
--- 
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  selector:
    app: trips
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80