# This is SecretProviderClass example using aad-pod-identity for authentication with Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-demok8svault-user-msi
spec:
  parameters:
    userAssignedIdentityID: "b44e66ff-614d-4d58-8119-de032fdce85b"
